<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="VivoBook" failures="1" tests="6" name="errorvalidationsTest" time="30.046" errors="0" timestamp="2024-09-22T00:28:14 IST">
  <testcase classname="com.remedi.test.ErrorValidationsTest" name="blankUsername_validpassword" time="1.007">
    <skipped/>
  </testcase> <!-- blankUsername_validpassword -->
  <testcase classname="com.remedi.test.ErrorValidationsTest" name="blankUsername_validpassword" time="1.027">
    <failure type="java.lang.AssertionError" message="expected [Please Provide Username] but found [Please Provide Password]">
      <![CDATA[java.lang.AssertionError: expected [Please Provide Username] but found [Please Provide Password]
at com.remedi.test.ErrorValidationsTest.blankUsername_validpassword(ErrorValidationsTest.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- blankUsername_validpassword -->
  <testcase classname="com.remedi.test.ErrorValidationsTest" name="blankusername_blankpassword" time="0.961"/>
  <testcase classname="com.remedi.test.ErrorValidationsTest" name="invalidUsername_validPassword" time="1.447"/>
  <testcase classname="com.remedi.test.ErrorValidationsTest" name="validUsername_blankpassword" time="0.915"/>
  <testcase classname="com.remedi.test.ErrorValidationsTest" name="validUsername_invalidPassword" time="1.228"/>
</testsuite> <!-- errorvalidationsTest -->
